import { Item } from '@/types/Item';

export const itemInitialState: Item & { selected: number[] | undefined } ={
  id: undefined,
  supplier_id: undefined,
  code: '',
  name: '',
  item_number: undefined,
  variations1: '',
  variations2: '',
  variations3: '',
  variations4: '',
  explanation: '',
  explanation_details: '',
  name_note: '',
  name_label: '',
  is_sell: true,
  purchase_price: undefined,
  sales_price: 0,
  special_sale_id: undefined,
  sales_unit_price: undefined,
  purchase_unit_price: undefined,
  sample_price: undefined,
  is_discontinued: false,
  discontinued_at: '',
  is_display: false,
  is_point_rebates: false,
  number_reservations: undefined,
  is_shipping_fee: false,
  is_cash_delivery_fee: false,
  additional_shipping_fee: undefined,
  is_payment_id1: false,
  is_payment_id2: false,
  is_payment_id3: false,
  is_payment_id4: false,
  is_payment_id5: false,
  payErrorMessage: '',
  display_status: 0,
  variItems: [['']],      // variItemsとimageListの要素数・要素内容は対（要素0の管理IDまたはnewで判定）
  backVariItems: [['']],
  imageList: [['']],      // variItemsとimageListの要素数・要素内容は対（要素0の管理IDまたはnewで判定）
  shipping_pay: undefined,

  category_id: undefined,
  category_name: '',
  supplier_name: '',
  domestic_stocks: undefined,
  overseas_stocks: undefined,
  is_set_item: false,

  item_id: undefined,
  is_sales_members_only: false,
  start_at: '',
  end_at: '',
  special_sale_price: 0,
  refund_rate: 0,
  codeList: [],
  categoryList: [
    {
      combId: undefined,
      categoryId: null,
      name: '',
      status: 'new1',
      initialcategoryId: undefined,
    }
  ],
  specialSalesList: [],
  specialSalesDelFlag: false,
  selected: undefined,
  preImageList: [['']],
  combination_id: undefined,
  combIdList: [],
  send_trader: undefined,
  send_personal: undefined,
  type_status: undefined,
  type_name: '',
  file_name: '',
  document_id: undefined,
  pdf: undefined,
  documentFileList: [],
  categoryListAll: [],
  dataBaceAllCodeList: [],
  initialCode: '',
};